GET http://localhost:3000/api/certificates/1049625178

POST http://localhost:3000/api/certificates/add
Content-Type: application/json

{
    "name": "Andrés Alejandro Yela Bastidas",
    "id": "1087619754",
    "courseTitle": "METROLOGÍA BÁSICA"
}