GET https://certificados-backend.onrender.com/api/certificates/validate/ME-UZDY-7732

GET https://certificados-backend.onrender.com/api/certificates

GET https://certificados-backend.onrender.com/api/certificates/5428889

POST http://certificados-backend.onrender.com/api/certificates/add
Content-Type: application/json

{
    "name": "Andrés Alejandro Yela Bastidas",
    "id": "1087619754",
    "courseTitle": "VERIFICACIÓN DE MÉTODOS"
}