GET https://dev-6tbiy7tc5eqhqb7k.us.auth0.com/userinfo
Authorization: 'Bearer eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIiwiaXNzIjoiaHR0cHM6Ly9kZXYtNnRiaXk3dGM1ZXFocWI3ay51cy5hdXRoMC5jb20vIn0..6G7vISGtLhHBb2KY.1IWBViJ5TXGyE6GU0bULyHnUH2bY5cLBisUzat0FVLW9vTU677wttu_jHJ0U6Tg307-blINiVXwMjsbJ364sgqCwjAy7tHgRII1TDnby-v9pEQ5QzVJxFy1YTxG6eO4yoFncduYywOooD12S9iiHY61-KB_DoRLCGRkukutDvZns0WYrPWOy-o0d_CFuLGU-EnhEMRrou995M9JOnlwwPvjDULymILN8Sfmhx3LRfYD3BdqmWFoUOe5Ch5SF19ha2HP8y6ffcbAgZzh4qJBqbw5g-dCHWkvEi0jXpD_zrHvO2zD5Htg.JErf5FyfTzkf-RFy25fY4w'