POST http://certificados-backend.onrender.com/api/certificates/add
Content-Type: application/json

{
    "name": "Yojan Gonzalez",
    "id": "1082806377",
    "email": "yojangonzalez431@gmail.com",
    "courseTitle": "METROLOGÍA BÁSICA"
}