POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "name": "Andrés Alejandro Yela Bastidas",
    "id": "1087619754",
    "email": "andres.alejo.yela@gmail.com",
    "password": "12345678"
}