POST http://certificados-backend.onrender.com/api/auth/register
Content-Type: application/json

{
    "name": "Juan Andres Herrera Aroca",
    "id": "1003828893",
    "email": "juanherrera11727@gmail.com",
    "password": "990226Aayb++"
}