POST http://certificados-backend.onrender.com/api/certificates/add
Content-Type: application/json

{
    "name": "Damaris Joanta Pulido Rolón",
    "id": "1049625178",
    "courseTitle": "INDICADORES DE GESTIÓN"
}