POST http://localhost:3000/api/certificates/add
Content-Type: application/json

{
    "name": "Julián Andrés Nontien Cuervo",
    "id": "1057597060",
    "email": "nontienjulian95@gmail.com",
    "courseTitle": "ISO/IEC 17043:2010 ENSAYOS DE APTITUD"
}
